### ISSUE TITLE
Make baseline folder configurable?

### ISSUE THREAD

**Issue by cdeil** [astrofrog/pytest-mpl#7]
At the moment I think the reference images have to be in a folder called `baseline`.

A common use case could be that people want to store the baseline images outside their code repo to keep it small.

Can you make this configurable somehow?

(a small comment about the docs: at first I was confused from the example in the readme where you have `py.test --mpl-generate-path=images ...` and then say the generated images have to be in `baseline` ... why not generate them in `baseline` from the start and check them there? Maybe this can be explained a little bit more clearly by changing to `baseline` directly or to explicitly mention that the files have to be copied over from `images` to `baseline`?)

**Comment by astrofrog** [comment]
Hehe, I implemented independently just before finding your issue :) See 06df911f5a1757cd4be1638ab84ebd878f999894

**Comment by astrofrog** [comment]
The reason for not generating them in the 'right' place is that for astropy packages, the tests are not run from the source package but from the build package, so the images would be generated in the temporary build directory. But maybe it would indeed be more sensible to have the example have ``baseline`` as the example directory instead of ``images``.

**Comment by cdeil** [comment]
@astrofrog – Thanks!

I think expanding on this a little bit more in the README would be good, especially give an example where the user writes and reads the images to any folder they like --- the usual use case will be a sub-folder in their repo where they execut `python setup.py test` or `py.test` .. maybe they have to give a full path then?

**Comment by astrofrog** [comment]
@cdeil - I've just made some improvements to the README - could you look over it and let me know what you think before I make further changes?

**Comment by cdeil** [comment]
The description in the README is clearer now, thanks!

But it's still not clear to me whether I can set the `MPL_BASELINE_PATH` (made up, doesn't exist yet, I think) globally:
```
  --mpl                 Enable comparison of matplotlib figures to reference
                        files
  --mpl-generate-path=MPL_GENERATE_PATH
                        directory to generate reference images in
```

I want to have this configured once for my package, and not repeat this as a `baseline_dir` option in every `mpl_image_compare` test:
```
@pytest.mark.mpl_image_compare(baseline_dir='baseline_images',
                               filename='other_name.png')
```
Possible?

**Comment by astrofrog** [comment]
@cdeil - ah, I see what you mean. That isn't possible but I can add this as a new option.

**Comment by astrofrog** [comment]
@cdeil - see #8 :)

**Comment by astrofrog** [comment]
Done in #8
